#server.port=8085
#
#spring.datasource.url=jdbc:sqlite:catalog.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#
#spring.sql.init.mode=always
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
##spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

server.port=8081
#server.port=8086

spring.datasource.url=jdbc:sqlite:catalog.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always