services:
  catalog:
    build: ./Catalog-Service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/data/catalog.db
    volumes:
      - ./Catalog-Service/catalog.db:/app/data/catalog.db

  order:
    build: ./Order-Service
    ports:
      - "8082:8082"
    environment:
      CATALOG_BASE_URL: http://catalog:8081
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/data/orders.db
    volumes:
      - ./Order-Service/orders.db:/app/data/orders.db
    depends_on:
      - catalog

  frontend:
    build: ./frontend-service
    ports:
      - "8083:8083"
    environment:
      CATALOG_URLS: http://catalog:8081/api/catalog
      ORDER_URLS: http://order:8082/api/order
    depends_on:
      - catalog
      - order
