server.port=8082
catalog.base-url=${CATALOG_BASE_URL:http://localhost:8081}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:orders.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
